# .github/workflows/cd-pipeline.yml

name: CD - Deploy Services to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  AKS_CLUSTER_NAME: 'SIT722-AKS-Cluster'
  AKS_RESOURCE_GROUP: 'SIT722-8-1P-RG'
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy_to_aks:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Kubernetes context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}

      # ✅ FIX: This step has been re-added to ensure the deployment object exists.
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/ --force
      
      - name: Update deployments with new image tag
        run: |
          # ✅ FIX: Changed to match the deployment names in your Kubernetes manifests
          kubectl set image deployment/frontend frontend-container=${{ env.ACR_LOGIN_SERVER }}/frontend:latest
          kubectl set image deployment/product-service-w08e1 product-service-container=${{ env.ACR_LOGIN_SERVER }}/product_service:latest
          kubectl set image deployment/order-service-w08e1 order-service-container=${{ env.ACR_LOGIN_SERVER }}/order_service:latest
      
      # ✅ FIX: This step ensures environment variables from the ConfigMap are applied to the frontend deployment.
      - name: Update frontend with ConfigMap
        run: |
          kubectl patch deployment frontend --type='json' -p='[{"op": "add", "path": "/spec/template/spec/containers/0/envFrom", "value": [{"configMapRef": {"name": "frontend-config"}}]}]'
      
      - name: Verify deployments
        run: |
          echo "Waiting for deployments to roll out..."
          # ✅ FIX: Changed to match the deployment names in your Kubernetes manifests
          kubectl rollout status deployment/frontend
          kubectl rollout status deployment/product-service-w08e1
          kubectl rollout status deployment/order-service-w08e1
          echo "✅ All services deployed successfully!"

      - name: Logout from Azure
        if: always()
        run: az logout